# Generated by Django 4.1.4 on 2022-12-31 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_point_transaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="amount",
        ),
    ]
